### ISSUE TITLE
Running the Tracking functions.

### ISSUE THREAD

**Issue by spranjal25** [LoCO-AUV/target_following#1]
I want to integrate the object tracking + Following functionality in the loco-auv simulation. We have the loco-auv working as per the keyboard_teleop commands (w,a,s,d etc.). The camera is also accessible and verified that it interacts with the surroundings. How to integrate this approach of following + tracking with the camera in loco-auv? Can someone point me in the right direction

**Comment by junaedsattar** [comment]
This is not a LoCO specific issue, and I have already contacted you over email about this. We're not going to be providing tutorials for general robot behavior.
